services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: no
    healthcheck:
      test: [ "CMD", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  app-network: 
    driver: bridge